### ISSUE TITLE
Re-implement because of the deprecation of Ember.logger

### ISSUE THREAD

**Issue by mansona** [MindscapeHQ/ember-cli-raygun#21]
Howdy 👋 

I'm just raising this issue because it's something that is going to affect you directly quite soon, there is an RFC in Ember that is currently going into Final Comment Period that is planning to remove support for Ember.logger: https://github.com/emberjs/rfcs/pull/297

I don't know if I have enough knowledge of what is going on in your internals to comment directly on that RFC but I would strongly recommend that you do 👍 

Also if you accept what they are doing we should start development on the migration.

**Comment by lupestro** [comment]
The chief impact from an implementation perspective will be in `addon/initializers/ember-cli-raygun.js`. The calls to `Ember.Logger.info` in that module are replaceable with calls to `console.info` without much impact, but the following lines may take a little thought about what logging you intended to capture. Projects that are specifically logging interceptors are often going after console logging methods as well, but I understand there are a lot of tradeoffs, and I'm not sure of the tradeoffs you were considering in your design.
```
    Ember.Logger.error = function (message, cause, stack) {
      defaultErrorHandler(message, cause, stack);
      Raygun.send(new Error(message + " (" + cause + ")"), null, {
        cause: cause,
        stack: stack
       });
    };
```
Thanks @mansona for raising this issue here. My survey of addons as I prepared the RFC covered several of the heavy-hitters, looking for specific issues they were likely to have, but I readily admit I didn't get to them all.

**Comment by nikz** [comment]
Hi @mansona and @lupestro - please check the latest version in `main` - we've now replaced this deprecated usage for you 😄
